# Generated by Django 3.2 on 2021-04-29 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('degree', models.CharField(choices=[('bachelor', 'Bachelor'), ('specialty', 'Specialty'), ('magistracy', 'Magistracy'), ('SSE', 'secondary special'), ('postgraduate', 'Postgraduate')], help_text='Current studying level', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(help_text='Name uses on authorization page', max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('avatar', models.ImageField(upload_to='')),
                ('current_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group')),
            ],
        ),
    ]
