# Generated by Django 3.1.4 on 2021-05-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210512_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='current_group',
            new_name='current_class',
        ),
    ]
