# Generated by Django 3.1.4 on 2021-04-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name of achievement', max_length=30)),
                ('courses', models.FloatField(help_text='Number of courses for full education program', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='StudProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('avg_mark', models.FloatField(help_text='Exams average rating', max_length=3)),
                ('group', models.CharField(help_text='Student group', max_length=30)),
                ('role', models.CharField(help_text='Choosing role of student', max_length=50)),
                ('fk_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.grade')),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.studprofile')),
            ],
        ),
    ]
